- id: pre-commit-sort
  name: Sort pre-commit files
  entry: pre-commit-sort
  language: rust
  files: ^.pre-commit-{config,hooks}.yaml$
  types:
  - text
  description: Sort .pre-commit-config.yaml & .pre-commit-hooks.yaml
