[package]
name = "pre-commit-sort"
version = "0.1.0"
edition = "2021"
authors = ["Guilhem Saurel <guilhem.saurel@laas.fr>"]
description = "Sort pre-commit files"
keywords = ["yaml", "serde", "serialization", "ci", "pre-commit"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/nim65s/pre-commit-sort"

[dependencies]
anyhow = "1.0.71"
serde = { version = "1.0.163", features = ["derive"] }
serde_with = "3.0.0"
serde_yaml = "0.9.21"
thiserror = "1.0.40"

[dev-dependencies]
indoc = "2.0.1"
